#!/usr/bin/env bash

#
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#

set -e

RUSTFLAGS="--cfg s2n_quic_unstable" cargo clippy --all-features --all-targets -- -D warnings
RUSTFLAGS="--cfg s2n_quic_unstable" cargo test --doc
